DELIMITER //
CREATE FUNCTION get_monthly_promo() RETURNS DECIMAL(5,2) DETERMINISTIC
BEGIN
    IF MONTH(NOW()) = 12 THEN RETURN 20.00;
    ELSEIF MONTH(NOW()) = 8 THEN RETURN 10.00;
    ELSE RETURN 0.00;
    END IF;
END  //
DELIMITER ;
